name: cmt
channels:
  - conda-forge
  - dnachun
dependencies:
  - cartopy
  - cmocean
  - bottleneck
  - dasel
  - datashader
  - dtale
  - fire
  - fx
  - fzf
  - geoviews
  - hvplot
  - ipyleaflet
  - ipykernel
  - ipython
  - ipywidgets
  - jq
  - lux
  - nodejs
  #- numba
  - panel
  - pip
  - pip
     - pandasai
  - polars
  - pyproj
  - python<3.13
  - python-duckdb
  - rasterio
  - rio-xarray
  - zarr
  - rioxarray
  - session-info
  - s5cmd
  - speedtest-cli
  - ydata-profiling
  #- r-base
  #- r-tidyverse
  #- r-raster
  #- r-ncdf4
  #- r-rgdal
  #- r-ggplot2
  #- r-lubridate
  #- r-sf
  #- r-leaflet
  #- r-terra
  #- r-rastervis
  #- r-rnaturalearthdata
  #- r-rnaturalearth
  #- r-codetools
  #- r-httr
  #- r-ncmeta
  #- r-tidync
