#!/bin/bash

# Add aliases to .bashrc only if they don't already exist
if ! grep -q "alias v1=" ~/.bashrc; then
    echo 'alias v1="source v1-latest/bin/activate"' >> ~/.bashrc
fi
if ! grep -q "alias pre=" ~/.bashrc; then
    echo 'alias pre="source pre-release/bin/activate"' >> ~/.bashrc
fi
if ! grep -q "alias v2=" ~/.bashrc; then
    echo 'alias v2="source v2-branch/bin/activate"' >> ~/.bashrc
fi

uv venv v1-latest
source v1-latest/bin/activate
uv pip install "copernicusmarine<2.0.0"
deactivate

uv venv pre-release
source pre-release/bin/activate
uv pip install 'copernicusmarine>=2.0.0a2'
deactivate

uv venv v2-branch
source v2-branch/bin/activate
uv pip install git+https://github.com/mercator-ocean/copernicus-marine-toolbox@copernicusmarine-toolbox-v2
deactivate
