#!/bin/bash

uv venv v1-latest
source v1-latest/bin/activate
uv pip install copernicusmarine
deactivate
uv venv pre-release
source pre-release/bin/activate
uv pip install copernicusmarine>=2.0.0a2
deactivate
uv venv v2-branch
source v2-branch/bin/activate
uv pip install git+https://github.com/mercator-ocean/copernicus-marine-toolbox@copernicusmarine-toolbox-v2
deactivate
