name: netcdf-zarr
channels:
  - conda-forge
dependencies:
  - hdf5
  - zlib
  - curl
  - libcurl
  - cmake =3.29
  - make
  - gcc_linux-64
  - gxx_linux-64
  - libzip
  - blosc
  - zstd
  - git
  - pkg-config
  - openssl
