#!/bin/bash

wget "https://atlas.mercator-ocean.fr/s/dBY8WJN86RxoNYG/download" -O cyclone-ready.tar.gz
tar -xvf cyclone-ready.tar.gz
rm -rf cyclone-ready.tar.gz

wget "https://atlas.mercator-ocean.fr/s/N55zaDPrmWNneg9/download" -O essentials-python-manipulation.tar.gz
tar -xvf essentials-python-manipulation.tar.gz
rm -rf essentials-python-manipulation.tar.gz

uv venv
source .venv/bin/activate
uv pip install copernicusmarine ipykernel ipywidgets matplotlib rioxarray geopandas geoviews hvplot scipy netcdf4 cmocean
.venv/bin/python -m ipykernel install --user --name "Python-Marine"
